global.u_pixelH_Wave = shader_get_uniform(shWave,"pixelH")
global.u_pixelW_Wave = shader_get_uniform(shWave,"pixelW")
global.u_springs = shader_get_uniform(shWave,"springs")
global.u_springCount = shader_get_uniform(shWave,"springCount")
global.u_time = shader_get_uniform(shWave,"time")